---
openapi: 3.0.0
info:
  title: API_Example
  description: StudySwagger
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/GUMBOKIM/API_Example/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://jsonplaceholder.typicode.com
  description: JSON Place Holder API
- url: https://www.google.com
  description: Google API
paths:
  /todos/{id}:
    post:
      summary: Returns a user by ID
      parameters:
      - name: id
        in: path
        description: THe ID of the user to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/JSON:
              schema:
                $ref: '#/components/schemas/inline_response_200'
  /complete/search:
    get:
      summary: AutoCompleted Result Return
      parameters:
      - name: q
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: client
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: A text File
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        userId:
          type: integer
        id:
          type: integer
        title:
          type: string
        completed:
          type: boolean
