spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.11.201:1433;DatabaseName=TESTDB;schema=test;
    username: xingsoft
    password: password


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.example.springfilter.**


server:
  port: 8080

jwt:
  header-name: 'xing'

