spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    driver-class-name: org.h2.Driver
    username:  sa
    password:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      #show_sql: true
        format_sql:  true

logging.level:
  org.hibernate.SQL:  debug
  # org.hibernate.type: trace

server:
  port:  8089


