spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.11.201:1433;DatabaseName=TESTDB;schema=test;
    username: xingsoft
    password: password


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.example.toyproject.**


server:
  port: 8080

jwt:
  secret-key: returnblisskeyreturnblisskeyreturnblisskeyreturnblisskeyreturnblisskey
  access-token-expire-length: 3600000000
  refresh-token-expire-length: 3600000000
  header-name: 'returnbliss-bearar'

