openapi: 3.0.0
info:
  version: 1.0.0
  title: My_Api
  description: My API
servers:
  - url: http://localhost:3000/
    description: My API
paths:
  /adder:
    get:
      summary: Adder API
      parameters:
        - name: one
          in: query
          description: Frist Value
          required: true
          schema:
            type: integer
        - name: two
          in: query
          description: Second Value
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Added result
          content:
            text/plain:
              schema:
                type: integer
