server:
  port: 8088

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: kim
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: classpath:/repsitory/mapper/**